name: Bug Report
description: Напишите отчёт для будущего исправления ошибки
title: "[Bug]: "
labels: ["Баг"]
assignees:
  - demonwayne
body:
  - type: markdown
    attributes:
      value: |
        Напишите отчёт для будущего исправления ошибки!
  - type: dropdown
    id: project
    attributes:
      label: Выберите проект в котором найден баг
      description: В каком проекте найден баг?
      options:
        - MS bot
        - HB Public
        - Epitaka Bot
    validations:
      required: true
  - type: textarea
    id: bug-info
    attributes:
      label: Опишите баг
      description: Информация о баге
      placeholder: Подробно расскажите о баге.
    validations:
      required: true
  - type: textarea
    id: more-info
    attributes:
      label: Доп. Информация
      description: Любая дополнительная информация которая поможет в исправлении бага.
      placeholder: Любое дополнение
    validations:
      required: false
